# Generated by Django 5.0.6 on 2024-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Admin', 'Admin')], default='Seller', max_length=8),
        ),
    ]
