# Generated by Django 5.0.6 on 2024-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('Accessories', 'Accessories'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Garden', 'Garden'), ('Home', 'Home'), ('Kitchen', 'Kitchen'), ('Fruits', 'Fruits'), ('shoes', 'Shoes'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Travel', 'Travel'), ('Watches', 'Watches'), ('Others', 'Others')], max_length=40)),
                ('SubCategory', models.CharField(choices=[('Accessories', 'Accessories'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Garden', 'Garden'), ('Home', 'Home'), ('Kitchen', 'Kitchen'), ('Fruits', 'Fruits'), ('shoes', 'Shoes'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Travel', 'Travel'), ('Watches', 'Watches'), ('Others', 'Others')], max_length=40)),
                ('Brand', models.CharField(choices=[('Samsung', 'Samsung'), (' Apple', ' Apple'), ('Acer', 'Acer'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Toshiba', 'Toshiba'), ('Xiaomi', 'Xiaomi'), ('Other', 'Other')], max_length=40)),
                ('Unit', models.CharField(choices=[('pc', 'pc'), ('kg', 'kg'), ('box', 'box'), ('liter', 'liter'), ('m', 'm'), ('cm', 'cm')], max_length=40)),
                ('SKU', models.CharField(max_length=300)),
                ('Minimum_Quantity', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Description', models.TextField()),
                ('Tax', models.CharField(choices=[('Sales Tax', 'Sales Tax'), ('Excise Tax', 'Excise Tax')], max_length=30)),
                ('Discount', models.CharField(choices=[('percentage', 'Percentage'), ('Doller-Amount', 'Doller-Amount'), ('Buy-one-get-one', 'Buy-one-get-one'), ('volume-amount', 'Volume-Amount'), ('seasonal', 'Seasonal'), ('Early-Bird', 'EarlyBird'), ('Free-shipings', 'Free-Shipings'), ('Membership', 'Membership'), ('Referral', 'Referral')], max_length=40)),
                ('price', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('product_image', models.ImageField(upload_to='product_image/')),
            ],
        ),
    ]
