# Generated by Django 5.0.6 on 2024-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='Created_by',
            field=models.CharField(choices=[('Seller', 'Seller'), ('admin', 'Admin')], max_length=8, null=True),
        ),
    ]
