# Generated by Django 5.0.6 on 2024-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productsmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='Brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Acer', 'Acer'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Toshiba', 'Toshiba'), ('Xiaomi', 'Xiaomi'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='Created_by',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Admin', 'Admin')], max_length=8, null=True),
        ),
    ]
